vich_uploader:
    db_driver: orm

    mappings:
        album_image:
            uri_prefix: /images/albums
            upload_destination: '%kernel.project_dir%/public/images/albums'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
